# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'sc-sonarcloud'
    organization: '2194189infonuagique'
    scannerMode: 'dotnet'
    projectKey: '2194189Infonuagique_SecAppTP5'
    projectName: 'SecAppTP5'

- task: DotNetCoreCLI@2
  inputs:
         command: 'restore'
         projects: '**/*.csproj'
         feedsToUse: 'select'
  displayName: 'restaurer les packages'

- task: DotNetCoreCLI@2
  inputs:
         command: 'build'
         projects: '**/*.csproj'
         arguments: '--configuration $(buildConfiguration)'
  displayName: 'Génération de la solution'

- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'